# Changes here will be overwritten by Copier
_commit: 0.16.5
_src_path: gh:pawamoy/copier-pdm
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
insiders: true
project_description: MkDocs plugin to generate a manpage from the documentation site.
project_name: MkDocs Manpage
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-manpage
python_package_import_name: mkdocs_manpage
repository_name: mkdocs-manpage
repository_namespace: pawamoy
repository_provider: github.com

