# Changes here will be overwritten by Copier
_commit: 1.2.6
_src_path: gh:pawamoy/copier-pdm
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2023'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: true
insiders_email: insiders@pawamoy.fr
insiders_repository_name: mkdocs-manpage
project_description: MkDocs plugin to generate a manpage from the documentation site.
project_name: MkDocs Manpage
public_release: true
python_package_command_line_name: ''
python_package_distribution_name: mkdocs-manpage
python_package_import_name: mkdocs_manpage
repository_name: mkdocs-manpage
repository_namespace: pawamoy
repository_provider: github.com

